import turtle
import math
# Set the background color
screen = turtle.Screen()
screen.bgcolor("lightpink")
# Create our turtle
t = turtle.Turtle()
t.color("black")
t.shape("turtle")
t.speed(0)
t.hideturtle()
# Define a function to draw and
# fill a rectangle with the given
# dimensions and color
def drawRectangle(t, width, height, color):
	t.fillcolor(color)
	t.begin_fill()
	t.forward(width)
	t.left(90)
	t.forward(height)
	t.left(90)
	t.forward(width)
	t.left(90)
	t.forward(height)
	t.left(90)
	t.end_fill()
# Define a function to draw and fill an equalateral right
# triangle with the given hypotenuse length and color. This
# is used to create a roof shape.
def drawTriangle(t, length, color):
	t.fillcolor(color)
	t.begin_fill()
	t.forward(length)
	t.left(135)
	t.forward(length / math.sqrt(2))
	t.left(90)
	t.forward(length / math.sqrt(2))
	t.left(135)
	t.end_fill()
# Define a function to draw and fill a parallelogram, used to
# draw the side of the house
def drawParallelogram(t, width, height, color):
	t.fillcolor(color)
	t.begin_fill()
	t.left(30)
	t.forward(width)
	t.left(60)
	t.forward(height)
	t.left(120)
	t.forward(width)
	t.left(60)
	t.forward(height)
	t.left(90)
	t.end_fill()
# Draw and fill the front of the house
t.penup()
t.goto(-250, -250)
t.pendown()
drawRectangle(t, 200, 200, "blue")
# Draw and fill the front door
t.penup()
t.goto(-220, -250)
t.pendown()
drawRectangle(t, 80, 120, "lightgreen")
# Front roof
t.penup()
t.goto(-250, -50)
t.pendown()
drawTriangle(t, 200, "magenta")
# Side of the house
t.penup()
t.goto(-50, -250)
t.pendown()
drawParallelogram(t, 120, 200, "yellow")
# Window
t.penup()
t.goto(-30, -130)
t.pendown()
drawParallelogram(t, 40, 60, "brown")
# Side roof
t.penup()
t.goto(-50, -50)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.left(30)
t.forward(120)
t.left(105)
t.forward(200 / math.sqrt(2))
t.left(75)
t.forward(120)
t.left(105)
t.forward(200 / math.sqrt(2))
t.left(45)
t.end_fill()
# Chimney
t.penup()
t.goto(-50, -50)
t.pendown()
drawRectangle(t, 30, 60, "gray")
# Smoke
t.penup()
t.goto(-40, -10)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(10)
t.end_fill()
t.penup()
t.goto(-35, -5)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(11)
t.end_fill()
t.penup()
t.goto(-30, 0)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(12)
t.end_fill()
t.penup()
t.goto(-25, 5)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(13)
t.end_fill()
t.penup()
t.goto(-20, 10)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(14)
t.end_fill()
turtle.done()
